generic routing handler
DieTechniker/3rdparty-privacy-proxy pull request #26
Opened 2022-07-14 13:44 UTC by kassimhoelting

... to handle get and post right

2022-07-18 07:06 UTC, renejahn requested changes

2022-07-18 07:06 UTC, renejahn commented on src/main/java/de/tk/opensource/privacyproxy/routing/RoutingHandler.java
> +				responseBodyBytes = IOUtils.toByteArray(responseBody.getInputStream());
Wird der InputStream immer wieder erzeugt, oder könnten wir den potenziell für nachfolgende Calls "leer"lesen?

2022-07-18 07:29 UTC, soeren-rtgr-tk requested changes

2022-07-18 07:29 UTC, soeren-rtgr-tk commented on src/main/java/de/tk/opensource/privacyproxy/routing/RoutingHandler.java
> +			addLegacyWhitelistedCookiesToRequest(httpRequest, request);
Kommentar ist hinfällig, wenn der Methodenname passt. Gleiches gilt für andere Codestellen

2022-07-18 07:29 UTC, soeren-rtgr-tk commented on src/main/java/de/tk/opensource/privacyproxy/routing/RoutingHandler.java
> +			final HttpHeaders responseHeaders =
smart geschachtelt, aber nicht mehr lesbar. Bitte auslagern in Methode und Variablen/Konstanten spendieren. Kommentar dann auch hinfällig.

2022-07-18 07:29 UTC, soeren-rtgr-tk commented on src/main/java/de/tk/opensource/privacyproxy/routing/RoutingHandler.java
>  public abstract class RoutingHandler {
wie schon im anderen PR beschrieben, ist die Klasse viel zu groß geworden. Ich bin dafür die Verantwortlichkeiten aufzuteilen und die großen Methoden zu verkleinern. Dabei können Kommentare durch sprechende Methodennamen ersetzt werden.

2022-07-18 07:29 UTC, soeren-rtgr-tk commented on src/main/java/de/tk/opensource/privacyproxy/routing/RoutingHandler.java
> +	protected HttpHeaders getResponseHeaders(final HttpHeaders sourceHeaders) {
Passt hier der Methodenname "getWhitelistedResponseHeaders" besser?

2022-07-18 07:29 UTC, soeren-rtgr-tk commented on src/main/java/de/tk/opensource/privacyproxy/routing/RoutingHandler.java
> +		// add provider specific response headers
Hier bitte auch den den Code in addProviderSpecificResponseHeaders auslagern.

2022-07-18 07:56 UTC, soeren-rtgr-tk requested changes

2022-07-18 07:56 UTC, soeren-rtgr-tk commented on src/main/java/de/tk/opensource/privacyproxy/util/ProxyHelper.java
> +			RequestConfig.custom().setConnectTimeout(ROUTING_TIMEOUT_IN_SECS * 1000)
Das sind hier eigentlich ROUTING_TIMEOUT_IN_MS, oder?

2022-07-20 09:42 UTC, soeren-rtgr-tk commented on src/main/java/de/tk/opensource/privacyproxy/config/proxy/HttpProxyConfig.java
> +		@Value("${http.proxyHost:''}") String proxyHost,
du könntest @Value auch so nutzen, dass der default-Value null ist "${http.proxyHost:#{null}}"

2022-07-20 09:53 UTC, soeren-rtgr-tk commented on src/main/java/de/tk/opensource/privacyproxy/util/ProxyHelper.java
>  	ProxyHelper(Proxy proxy, String nonProxyHosts) {
kann der nicht protected sein?

2022-07-20 09:55 UTC, soeren-rtgr-tk commented on src/main/java/de/tk/opensource/privacyproxy/util/ProxyHelper.java
>  	ProxyHelper(Proxy proxy, String nonProxyHosts) {
kann der nicht protected sein?

2022-07-20 14:59 UTC, renejahn commented on src/main/java/de/tk/opensource/privacyproxy/routing/RoutingHandler.java
> +		} catch (Exception e) {
Wenn wir Exception direkt fangen, könnten wir ungewollt andere Runtime-Exceptions verschlucken. Prinzipiell sollte man das also vermeiden, wenn möglich. Außerdem finde ich explizit eigentlich immer besser als implizit :P

2022-07-20 15:00 UTC, renejahn commented on src/main/java/de/tk/opensource/privacyproxy/routing/RoutingHandler.java
> +				responseBodyBytes = IOUtils.toByteArray(responseBody.getInputStream());
Dann seh ich kein Problem. Hatte das nur bei anderen Frameworks mal, dass ein Stream für spätere Verarbeitung plötzlich leer war und wollte nur sichergehen :+1:

2022-07-20 15:18 UTC, renejahn requested changes

2022-07-20 15:18 UTC, renejahn commented on src/main/java/de/tk/opensource/privacyproxy/util/ProxyHelper.java
>  	private String nonProxyHosts;
Wir greifen auf dieses Setting an mehreren Stellen zu, evtl. wäre es noch sinnvoll eine dedizierte Settingklasse zu spendieren, die für ProxySettings die Properties einliest und dann an den bisherigen Stellen injected wird?

2022-07-20 15:18 UTC, renejahn commented on src/main/java/de/tk/opensource/privacyproxy/util/RestTemplateProxyCustomizer.java
> +	public RestTemplateProxyCustomizer(
Funktioniert das ganze ohne die `@Injected`/`@Autowired`-Annotation am Konstruktor? Weißt Spring automatisch, wie der Service erzeugt wird?

2022-07-21 07:36 UTC, kassimhoelting commented on src/main/java/de/tk/opensource/privacyproxy/util/ProxyHelper.java
>  	ProxyHelper(Proxy proxy, String nonProxyHosts) {
findest du Package Protection für weniger Sichtbarkeit nicht passender?

2022-07-21 11:11 UTC, kassimhoelting commented on src/main/java/de/tk/opensource/privacyproxy/util/RestTemplateProxyCustomizer.java
> +	public RestTemplateProxyCustomizer(
Funktioniert ohne, sofern du nur einen Constructor hast

2022-07-22 08:10 UTC, renejahn approved these changes

2022-07-22 11:52 UTC, kassimhoelting commented on src/main/java/de/tk/opensource/privacyproxy/util/ProxyRoutePlanner.java
> +				new DefaultProxyRoutePlanner(httpHost) {
Schiebe ich in einem zweiten PR nach

2022-07-22 11:53 UTC, merged